import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import dynamic from 'next/dynamic';

import coverImage from '../../public/CoverImage.jpg';
import settingsIcon from '../../public/Settings.svg';

import styles from 'styles/Home.module.scss'
import Chip from 'components/elements/Chip/Chip';
import Button from 'components/elements/Button/Button';
import Input from 'components/elements/Input/Input';

const Chips = dynamic(
  () => import('components/templates/Chips/Chips'),
  { ssr: false }
)

const Slider = dynamic(
  () => import('components/templates/Slider/Slider'),
  { ssr: false }
)
 
const Home: NextPage = () => {

  return (
    <div>
      <Head>
        <title>Welcome</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>

      <main className={styles.main}>
          
        <div className={styles.main__coverImage}>
          <Image
            src={coverImage}
            alt="Background image"
            layout="fill"
            priority
          />
        </div>
        <section className={styles.main__sliderContainer}>
          <Slider 
            slides={[
              'Испания',
              'Франция',
              'Сент Винсент и Гренадины',
              'Португалия',
              'Саудовская Аравия'
            ]}
          />
        </section>

        <section className={styles.main__description}>
            <p>Мир Breezzor огромный, исследуй его!</p>
        </section>
        <section className={styles.main__actions}>
          <article className={styles.actions__chips}>
            <Chips chips={['Пляжи', 'Breezzor Pass', 'Впечатления', 'Маршруты']} initialActive={0}/>
          </article>
          <article className={styles.actions__search}>
            <Input endAdornment={<div className={styles.search__endAdorment}><Image alt="Settings" src={settingsIcon} /></div>} placeholder="Поиск по стране, региону, городу, название пляжа" width="740px"/>
          </article>
          <article className={styles.actions__buttons}>
            <Button variant="outlined"> На карте</Button>
            <Button variant="contained"> Все пляжи страны</Button>
          </article>
        </section>
      </main>
    </div>
  )
}

export default Home
